version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    ports:
      - '3309:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=MYSQL_RANDOM_ROOT_PASSWORD
        - MYSQL_DATABASE=symfony_products
        - MYSQL_USER=sf_app
        - MYSQL_PASSWORD=foobar
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
